generation:
  app: "GTABLE"
  run_type: "generation"
  real_data: /home/forcebot/project/gtable/examples/adults/data/adult.csv
  metadata: /home/forcebot/project/gtable/examples/adults/data/adult.json
  save_data: data/Civilian/balance_Civilian-15000
  save_checkpoints_steps: 1000
  epochs: 300
  cuda_visible_devices: 2
  g_penalty: 0.5
  n_critic: 10
  output: /home/forcebot/project/gtable/examples/adults/output/fake_gtable_adults.csv
  separated_embedding: true
  continuous_embeddding: 'Bayesian_Gaussian_Norm'
  optim: adam
  learning_rate: 2e-4
  adam_beta1: 0.5
  adam_beta2: 0.9

  transformer_type: "gmm"

evaluate:
  app: "GTABLE"
  run_type: "evaluate"
  transformer_type: "gmm"
  real_data: /home/forcebot/project/gtable/examples/adults/data/adult.csv
  fake_data: /home/forcebot/project/gtable/examples/adults/output/fake_gtable_adults.csv
#  fake_data: data/Civilian/ctgan_civilians_15000_notebook_fake.csv
#  fake_data: data/Civilian/tablegan_civilians_15000_notebook_fake.csv

  features_col: ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status',
                 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss',
                 'hours-per-week', 'native-country']
  target_col: 'income'

  classify_tasks: ['xgboost', 'logistic_regression', 'random_forest', 'decision_tree', 'mlp']
#  classify_tasks: ['xgboost']
  classify_scores: [ 'F1_Score', 'Recall_Score', 'Precision_Score']

#  regression_tasks: ['random_forest_regr', 'lasso', 'ridge', 'elastic_net']
#  regression_scores: ['mse', 'mae', 'mape', 'rmse']

#  visual: ['mean_std', 'cumsums', 'distributions', 'correlation', 'pca']
#  visual: ['correlation']

  continuous_statistics: ['min', 'max', 'mean', 'median', 'std', 'var']
  discrete_statistics: ['min', 'max', 'mean', 'median', 'std', 'var']
