preprocess:
  app: "table"
  work_model: "preprocess"
  data_type: "csv"
  sep: ","
  train_input: data/Civilian/Civilian_textual.csv
  valid_input: data/Civilian/Civilian_textual.csv
  target: "suicide"
  save_data: data/Civilian/Civilian



train:
  app: "table"
  work_model: "train"
  data: data/Civilian/Civilian


generation:
  app: "table"
  data: data/Civilian/Civilian
  project_dir: "/home/forcebot/project/privacy-analytics"
  work_model: "generation"
