preprocess:
  work_model: preprocess
  data_type: "csv"
  sep: ","
  train_input: data/Civilian/Civilian_textual.csv
  valid_input: data/Civilian/Civilian_textual.csv
  target: "suicide"
  save_data: data/Civilian/Civilian



train:
  work_model: train
  data:  data/Civilian/Civilian


predict:
  work_model: translate
